// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package atlusdb

type Parishioner struct {
	ID           string
	Name         string
	City         string
	Email        string
	IsRegistered bool
	Members      int32
}
