// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package atlusdb

import (
	"context"
	"database/sql"
)

const createParishioner = `-- name: CreateParishioner :execresult
INSERT INTO parishioners (
  name, city, email, is_registered, members
) VALUES (
  ?, ?, ?, ?, ?
)
`

type CreateParishionerParams struct {
	Name         string
	City         string
	Email        string
	IsRegistered bool
	Members      int32
}

func (q *Queries) CreateParishioner(ctx context.Context, arg CreateParishionerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createParishioner,
		arg.Name,
		arg.City,
		arg.Email,
		arg.IsRegistered,
		arg.Members,
	)
}

const deleteParishioner = `-- name: DeleteParishioner :exec
DELETE FROM parishioners
WHERE id = ?
`

func (q *Queries) DeleteParishioner(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteParishioner, id)
	return err
}

const getParishioner = `-- name: GetParishioner :one
SELECT id, name, city, email, is_registered, members FROM parishioners
WHERE id = ?
`

func (q *Queries) GetParishioner(ctx context.Context, id string) (Parishioner, error) {
	row := q.db.QueryRowContext(ctx, getParishioner, id)
	var i Parishioner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Email,
		&i.IsRegistered,
		&i.Members,
	)
	return i, err
}

const listParishioners = `-- name: ListParishioners :many
SELECT id, name, city, email, is_registered, members FROM parishioners
ORDER BY name
`

func (q *Queries) ListParishioners(ctx context.Context) ([]Parishioner, error) {
	rows, err := q.db.QueryContext(ctx, listParishioners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parishioner
	for rows.Next() {
		var i Parishioner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Email,
			&i.IsRegistered,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParishioner = `-- name: UpdateParishioner :exec
UPDATE parishioners
SET name = ?,
  city = ?,
  email = ?,
  is_registered = ?,
  members = ?
WHERE id = ?
`

type UpdateParishionerParams struct {
	Name         string
	City         string
	Email        string
	IsRegistered bool
	Members      int32
	ID           string
}

func (q *Queries) UpdateParishioner(ctx context.Context, arg UpdateParishionerParams) error {
	_, err := q.db.ExecContext(ctx, updateParishioner,
		arg.Name,
		arg.City,
		arg.Email,
		arg.IsRegistered,
		arg.Members,
		arg.ID,
	)
	return err
}
